export type CrossLink = {
  lessonId: string;
  lessonPath: string;
  lessonTitle: string;
  lessonLevel: 1 | 2 | 3;
  hubPath: string;
  hubAnchor?: string;
  hubLabel: string;
  contextInLesson: string;
  contextInHub: string;
  /**
   * Полная лекция учебного пособия для этой же связи, если она есть.
   * hubPath/hubAnchor ведут в краткую версию хаба и остаются неизменными —
   * это второй, более глубокий уровень того же материала.
   */
  textbookRoute?: string;
};

export const CROSSLINKS: CrossLink[] = [
  // ── Урок 1.1: Что такое RL? ──
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/deep-rl", hubAnchor: "foundations", hubLabel: "Deep RL → Основы", contextInLesson: "MDP, награды, нейросети — расширение введения", contextInHub: "Введение в Уроке 1.1" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-3", hubLabel: "Математика → Глава 3. MDP", contextInLesson: "Формальное определение MDP, V/Q функции", contextInHub: "Введение в Уроке 1.1", textbookRoute: "/math-rl/textbook/part-6/03-mdp" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "4-уравнения-беллмана-и-дисконтирование", hubLabel: "Математика → Ряды и дисконтирование", contextInLesson: "Математика за γ и бесконечными суммами наград", contextInHub: "Введение в Уроке 1.1", textbookRoute: "/math-rl/textbook/part-1/04-bellman-and-discounting" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/algorithms/dqn", hubLabel: "Алгоритмы → DQN", contextInLesson: "Пример value-based метода", contextInHub: "Введение в Уроке 1.1" },

  // ── Урок 1.2: Установка окружения ──
  { lessonId: "1-2", lessonPath: "/courses/1-2", lessonTitle: "Установка окружения", lessonLevel: 1, hubPath: "/pytorch/cheatsheet", hubAnchor: "setup", hubLabel: "PyTorch → Установка", contextInLesson: "Установка PyTorch и проверка GPU", contextInHub: "Справка по установке (Урок 1.2)" },
  { lessonId: "1-2", lessonPath: "/courses/1-2", lessonTitle: "Установка окружения", lessonLevel: 1, hubPath: "/pytorch/cheatsheet", hubAnchor: "tensors", hubLabel: "PyTorch → Тензоры", contextInLesson: "Основы работы с тензорами", contextInHub: "Тензоры на практике (Урок 1.2)" },
  { lessonId: "1-2", lessonPath: "/courses/1-2", lessonTitle: "Установка окружения", lessonLevel: 1, hubPath: "/unity-ml-agents", hubAnchor: "installation", hubLabel: "Unity ML-Agents → Установка", contextInLesson: "Параллельная настройка Unity ML-Agents", contextInHub: "Подробности установки (Урок 1.2)" },

  // ── Урок 1.3: MDP и уравнения Беллмана ──
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-5", hubLabel: "Математика → Глава 5. Уравнения Беллмана", contextInLesson: "Рекурсивная структура функции ценности", contextInHub: "Интуитивный разбор Беллмана (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-6/05-bellman-equations" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-3", hubLabel: "Математика → Глава 3. MDP", contextInLesson: "Формальное описание MDP-среды", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-6/03-mdp" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-6", hubLabel: "Математика → Глава 6. Model-Free RL", contextInLesson: "Переход от DP к Model-Free методам", contextInHub: "Связка с Model-Free (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-6/06-model-free-rl" },

  // ── Урок 1.4: Q-Learning табличный ──
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/algorithms/dqn", hubLabel: "Алгоритмы → DQN", contextInLesson: "Q-Learning как табличный предшественник DQN", contextInHub: "Табличный Q-Learning (Урок 1.4)" },

  // ── Урок 1.5: CartPole ──
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/pytorch/cheatsheet", hubAnchor: "nn", hubLabel: "PyTorch → nn.Module", contextInLesson: "Построение простой нейросети для CartPole", contextInHub: "nn.Module в действии (Урок 1.5)" },
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/pytorch/cheatsheet", hubAnchor: "training", hubLabel: "PyTorch → Цикл обучения", contextInLesson: "Цикл обучения: forward → loss → backward → step", contextInHub: "Практический цикл обучения (Урок 1.5)" },
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/algorithms/dqn", hubLabel: "Алгоритмы → DQN", contextInLesson: "CartPole как базовая среда для проверки DQN", contextInHub: "Среда CartPole (Урок 1.5)" },
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/pytorch", hubLabel: "PyTorch Шпаргалка", contextInLesson: "Полный справочник PyTorch для RL-задач", contextInHub: "Основы PyTorch (Урок 1.5)" },

  // ── Урок 1.6: DQN с нуля ──
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/algorithms/dqn", hubLabel: "Алгоритмы → DQN", contextInLesson: "Полная реализация DQN: replay buffer, target network", contextInHub: "Детальная реализация DQN (Урок 1.6)" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/pytorch/cheatsheet", hubAnchor: "nn", hubLabel: "PyTorch → nn.Module", contextInLesson: "Архитектура Q-сети на nn.Module", contextInHub: "Пример Q-сети (Урок 1.6)" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-5", hubLabel: "Математика → Глава 5. Уравнения Беллмана", contextInLesson: "Математическая основа DQN — уравнение Беллмана", contextInHub: "Формула Беллмана в коде DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-6/05-bellman-equations" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-4", hubAnchor: "лекция-3-градиентный-спуск-и-его-варианты", hubLabel: "Математика → Оптимизация", contextInLesson: "Оптимизация Q-сети через SGD / Adam", contextInHub: "Оптимизация в контексте DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-5/03-gradient-descent-variants" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/deep-rl", hubAnchor: "algorithms", hubLabel: "Deep RL → Алгоритмы", contextInLesson: "DQN в контексте других Deep RL алгоритмов", contextInHub: "DQN — первый deep-метод (Урок 1.6)" },

  // ── Проект-1: "Баланс в 3D" ──
  { lessonId: "project-1", lessonPath: "/courses/project-1", lessonTitle: 'Проект-1: "Баланс в 3D"', lessonLevel: 1, hubPath: "/unity-projects/ball-balance", hubLabel: "Unity → Ball Balance", contextInLesson: "Полная реализация проекта в 3D Unity-среде", contextInHub: 'Родственный проект (Проект-1: "Баланс в 3D")' },
  { lessonId: "project-1", lessonPath: "/courses/project-1", lessonTitle: 'Проект-1: "Баланс в 3D"', lessonLevel: 1, hubPath: "/algorithms/dqn", hubLabel: "Алгоритмы → DQN", contextInLesson: "Применение DQN для задачи балансировки", contextInHub: 'Практическое применение DQN (Проект-1: "Баланс в 3D")' },
  { lessonId: "project-1", lessonPath: "/courses/project-1", lessonTitle: 'Проект-1: "Баланс в 3D"', lessonLevel: 1, hubPath: "/pytorch/cheatsheet", hubAnchor: "saving", hubLabel: "PyTorch → Сохранение", contextInLesson: "Сохранение обученной модели (state_dict)", contextInHub: 'Сохранение модели (Проект-1: "Баланс в 3D")' },

  // ── Урок 2.1: Policy Gradient ──
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/deep-rl", hubAnchor: "algorithms", hubLabel: "Deep RL → Алгоритмы", contextInLesson: "Policy Gradient как альтернатива value-based методам", contextInHub: "Теорема градиента политики (Урок 2.1)" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-4", hubAnchor: "лекция-2-вывод-градиента-политики", hubLabel: "Математика → Вывод градиента политики", contextInLesson: "Стохастический градиентный подъём для политики", contextInHub: "Оптимизация политики (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-5/02-policy-gradient-derivation" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/pytorch/cheatsheet", hubAnchor: "autograd", hubLabel: "PyTorch → Autograd", contextInLesson: "Autograd для вычисления градиента политики", contextInHub: "Autograd в контексте REINFORCE (Урок 2.1)" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-3", hubAnchor: "1-теория-вероятностей", hubLabel: "Математика → Вероятности", contextInLesson: "Логарифмические производные и REINFORCE", contextInHub: "Вероятностные основы градиента политики (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-4/01-probability-theory" },

  // ── Урок 2.2: PPO ──
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "clipped", hubLabel: "PPO → Clipped Objective", contextInLesson: "Детальный разбор формулы клиппинга", contextInHub: "Реализация clipped loss (Урок 2.2)" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "gae", hubLabel: "PPO → GAE", contextInLesson: "Generalized Advantage Estimation в PPO", contextInHub: "GAE на практике (Урок 2.2)" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "architecture", hubLabel: "PPO → Архитектура", contextInLesson: "Архитектура Actor-Critic сетей для PPO", contextInHub: "Actor-Critic архитектура (Урок 2.2)" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "implementation", hubLabel: "PPO → Реализация", contextInLesson: "Полная реализация PPO на PyTorch", contextInHub: "Код PPO из Урока 2.2" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "unity", hubLabel: "PPO → Unity", contextInLesson: "Запуск PPO-обучения в Unity ML-Agents", contextInHub: "PPO в Unity (Урок 2.2)" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-9", hubLabel: "Математика → Глава 9. Policy Gradients и Advantage", contextInLesson: "Математика GAE и advantage estimation", contextInHub: "Формула GAE (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-6/09-policy-gradients" },

  // ── Урок 2.3: Непрерывные действия ──
  { lessonId: "2-3", lessonPath: "/courses/2-3", lessonTitle: "Непрерывные действия и Actor-Critic", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "architecture", hubLabel: "PPO → Архитектура", contextInLesson: "Адаптация PPO для continuous action space", contextInHub: "Continuous PPO (Урок 2.3)" },
  { lessonId: "2-3", lessonPath: "/courses/2-3", lessonTitle: "Непрерывные действия и Actor-Critic", lessonLevel: 2, hubPath: "/unity-ml-agents", hubAnchor: "neural-networks", hubLabel: "ML-Agents → Нейросети", contextInLesson: "Настройка continuous actions в ML-Agents", contextInHub: "Непрерывные действия (Урок 2.3)" },
  { lessonId: "2-3", lessonPath: "/courses/2-3", lessonTitle: "Непрерывные действия и Actor-Critic", lessonLevel: 2, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Тренировка с continuous actions в Unity", contextInHub: "Тренировка Actor-Critic (Урок 2.3)" },
  { lessonId: "2-3", lessonPath: "/courses/2-3", lessonTitle: "Непрерывные действия и Actor-Critic", lessonLevel: 2, hubPath: "/pytorch/cheatsheet", hubAnchor: "nn", hubLabel: "PyTorch → nn.Module", contextInLesson: "Gaussian Policy через nn.Module", contextInHub: "Gaussian Policy (Урок 2.3)" },

  // ── Урок 2.4: Reward Shaping ──
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/deep-rl", hubAnchor: "practice", hubLabel: "Deep RL → Практика", contextInLesson: "Проектирование функции вознаграждения", contextInHub: "Reward shaping (Урок 2.4)" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Настройка наград в Unity-средах", contextInHub: "Настройка reward в ML-Agents (Урок 2.4)" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "6-дисконтирование-в-rl-и-его-влияние", hubLabel: "Математика → Дисконтирование в RL", contextInLesson: "Математическое обоснование reward shaping", contextInHub: "Ряды и дисконтирование (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-1/06-discounting-in-rl" },

  // ── Урок 2.5: Параллельные среды ──
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Запуск множества экземпляров среды в ML-Agents", contextInHub: "Параллелизм для ускорения обучения (Урок 2.5)" },

  // ── Урок 2.6: TensorBoard и W&B ──
  { lessonId: "2-6", lessonPath: "/courses/2-6", lessonTitle: "TensorBoard и W&B", lessonLevel: 2, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Мониторинг обучения ML-Agents через TensorBoard", contextInHub: "TensorBoard + ML-Agents (Урок 2.6)" },
  { lessonId: "2-6", lessonPath: "/courses/2-6", lessonTitle: "TensorBoard и W&B", lessonLevel: 2, hubPath: "/pytorch/cheatsheet", hubAnchor: "saving", hubLabel: "PyTorch → Сохранение", contextInLesson: "Логирование чекпоинтов и метрик", contextInHub: "Сохранение + логирование (Урок 2.6)" },

  // ── Проект 2: 3D-охотник ──
  { lessonId: "project-2", lessonPath: "/courses/project-2", lessonTitle: "Проект: 3D-охотник", lessonLevel: 2, hubPath: "/unity-ml-agents", hubAnchor: "neural-networks", hubLabel: "ML-Agents → Нейросети", contextInLesson: "Настройка нейросети для FoodCollector", contextInHub: "Конфигурация сети (Проект 2)" },
  { lessonId: "project-2", lessonPath: "/courses/project-2", lessonTitle: "Проект: 3D-охотник", lessonLevel: 2, hubPath: "/algorithms/ppo", hubLabel: "Алгоритмы → PPO", contextInLesson: "Применение PPO в проекте FoodCollector", contextInHub: "PPO на практике (Проект 2)" },
  { lessonId: "project-2", lessonPath: "/courses/project-2", lessonTitle: "Проект: 3D-охотник", lessonLevel: 2, hubPath: "/unity-projects/gridworld", hubLabel: "Unity → GridWorld", contextInLesson: "GridWorld как упрощённая аналогия FoodCollector", contextInHub: "Связь с FoodCollector (Проект 2)" },

  // ── Проект 3: Гоночный агент ──
  { lessonId: "project-3", lessonPath: "/courses/project-3", lessonTitle: "Проект: Гоночный агент", lessonLevel: 2, hubPath: "/unity-projects/racing", hubLabel: "Unity → Racing Car", contextInLesson: "Обучение агента управлению гоночным автомобилем", contextInHub: "Полный проект гоночного агента (Проект 3)" },
  { lessonId: "project-3", lessonPath: "/courses/project-3", lessonTitle: "Проект: Гоночный агент", lessonLevel: 2, hubPath: "/algorithms/ppo", hubAnchor: "unity", hubLabel: "PPO → Unity", contextInLesson: "PPO с continuous actions для гонок", contextInHub: "PPO в задаче вождения (Проект 3)" },

  // ── Урок 3.1: SAC ──
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/algorithms/sac", hubAnchor: "entropy", hubLabel: "SAC → Энтропия", contextInLesson: "Энтропийная регуляризация в SAC", contextInHub: "Теория энтропии (Урок 3.1)" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/algorithms/sac", hubAnchor: "architecture", hubLabel: "SAC → Архитектура", contextInLesson: "Twin Q-networks и reparameterization trick", contextInHub: "Архитектура SAC (Урок 3.1)" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/algorithms/sac", hubAnchor: "implementation", hubLabel: "SAC → Реализация", contextInLesson: "Полная реализация SAC на PyTorch", contextInHub: "Код SAC (Урок 3.1)" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/algorithms/sac", hubAnchor: "unity", hubLabel: "SAC → Unity", contextInLesson: "SAC-обучение в Unity ML-Agents", contextInHub: "SAC в Unity (Урок 3.1)" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/math-rl/module-5", hubAnchor: "глава-9", hubLabel: "Математика → Глава 9. Policy Gradients и энтропия", contextInLesson: "Математика soft value функций", contextInHub: "Энтропийная формула (Урок 3.1)", textbookRoute: "/math-rl/textbook/part-6/09-policy-gradients" },

  // ── Урок 3.2: MA-POCA и Self-Play ──
  { lessonId: "3-2", lessonPath: "/courses/3-2", lessonTitle: "MA-POCA и Self-Play", lessonLevel: 3, hubPath: "/unity-projects/soccer", hubLabel: "Unity → Soccer", contextInLesson: "Soccer как среда для multi-agent обучения", contextInHub: "Мультиагентная среда Soccer (Урок 3.2)" },
  { lessonId: "3-2", lessonPath: "/courses/3-2", lessonTitle: "MA-POCA и Self-Play", lessonLevel: 3, hubPath: "/deep-rl", hubAnchor: "algorithms", hubLabel: "Deep RL → Алгоритмы", contextInLesson: "Multi-Agent RL в семействе Deep RL", contextInHub: "Мультиагентные алгоритмы (Урок 3.2)" },
  { lessonId: "3-2", lessonPath: "/courses/3-2", lessonTitle: "MA-POCA и Self-Play", lessonLevel: 3, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Настройка self-play в ML-Agents", contextInHub: "Self-play тренировка (Урок 3.2)" },

  // ── Урок 3.3: Curriculum Learning ──
  { lessonId: "3-3", lessonPath: "/courses/3-3", lessonTitle: "Curriculum Learning", lessonLevel: 3, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Curriculum в YAML-конфигурации ML-Agents", contextInHub: "Настройка curriculum (Урок 3.3)" },
  { lessonId: "3-3", lessonPath: "/courses/3-3", lessonTitle: "Curriculum Learning", lessonLevel: 3, hubPath: "/deep-rl", hubAnchor: "practice", hubLabel: "Deep RL → Практика", contextInLesson: "Curriculum как инструмент стабильного обучения", contextInHub: "Curriculum learning (Урок 3.3)" },

  // ── Урок 3.4: GAIL ──
  { lessonId: "3-4", lessonPath: "/courses/3-4", lessonTitle: "Имитационное обучение (GAIL)", lessonLevel: 3, hubPath: "/deep-rl", hubAnchor: "algorithms", hubLabel: "Deep RL → Алгоритмы", contextInLesson: "GAIL в семействе Deep RL методов", contextInHub: "Imitation Learning (Урок 3.4)" },
  { lessonId: "3-4", lessonPath: "/courses/3-4", lessonTitle: "Имитационное обучение (GAIL)", lessonLevel: 3, hubPath: "/unity-ml-agents", hubAnchor: "training", hubLabel: "ML-Agents → Обучение", contextInLesson: "Запись и использование демонстраций в ML-Agents", contextInHub: "Демонстрации для GAIL (Урок 3.4)" },
  { lessonId: "3-4", lessonPath: "/courses/3-4", lessonTitle: "Имитационное обучение (GAIL)", lessonLevel: 3, hubPath: "/math-rl/module-4", hubAnchor: "лекция-2-вывод-градиента-политики", hubLabel: "Математика → Градиент политики", contextInLesson: "GAN-подобная оптимизация в GAIL", contextInHub: "Adversarial training (Урок 3.4)", textbookRoute: "/math-rl/textbook/part-5/02-policy-gradient-derivation" },

  // ── Урок 3.5: Деплой ONNX ──
  { lessonId: "3-5", lessonPath: "/courses/3-5", lessonTitle: "Деплой модели: ONNX", lessonLevel: 3, hubPath: "/pytorch/cheatsheet", hubAnchor: "onnx-export", hubLabel: "PyTorch → ONNX-экспорт", contextInLesson: "Экспорт PyTorch → ONNX формат", contextInHub: "ONNX-экспорт (Урок 3.5)" },
  { lessonId: "3-5", lessonPath: "/courses/3-5", lessonTitle: "Деплой модели: ONNX", lessonLevel: 3, hubPath: "/unity-ml-agents", hubAnchor: "installation", hubLabel: "ML-Agents → Установка", contextInLesson: "Интеграция ONNX-модели в Unity через Sentis", contextInHub: "ONNX → Sentis (Урок 3.5)" },

  // ── Урок 3.6: Оптимизация гиперпараметров ──
  { lessonId: "3-6", lessonPath: "/courses/3-6", lessonTitle: "Оптимизация гиперпараметров", lessonLevel: 3, hubPath: "/math-rl/module-4", hubAnchor: "лекция-3-градиентный-спуск-и-его-варианты", hubLabel: "Математика → Оптимизация", contextInLesson: "Математика поиска гиперпараметров", contextInHub: "Оптимизация гиперпараметров (Урок 3.6)", textbookRoute: "/math-rl/textbook/part-5/03-gradient-descent-variants" },
  { lessonId: "3-6", lessonPath: "/courses/3-6", lessonTitle: "Оптимизация гиперпараметров", lessonLevel: 3, hubPath: "/algorithms/ppo", hubAnchor: "implementation", hubLabel: "PPO → Реализация", contextInLesson: "lr, clip_range, n_epochs — настройка PPO", contextInHub: "Тюнинг PPO гиперпараметров (Урок 3.6)" },
  { lessonId: "3-6", lessonPath: "/courses/3-6", lessonTitle: "Оптимизация гиперпараметров", lessonLevel: 3, hubPath: "/fca-rl", hubAnchor: "fca-hyperparams", hubLabel: "FCA → Гиперпараметры", contextInLesson: "Анализ экспериментов через формальные понятия", contextInHub: "FCA-анализ гиперпараметров (Урок 3.6)" },

  // ── Урок 3.7: Архитектуры нейросетей ──
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/pytorch/cheatsheet", hubAnchor: "nn", hubLabel: "PyTorch → nn.Module", contextInLesson: "CNN, LSTM, Attention — реализация в PyTorch", contextInHub: "Архитектуры нейросетей (Урок 3.7)" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/math-rl/module-2", hubLabel: "Математика → Линейная алгебра", contextInLesson: "Матричные операции в свёрточных и рекуррентных сетях", contextInHub: "Линейная алгебра за архитектурами (Урок 3.7)", textbookRoute: "/math-rl/textbook/part-3/01-vectors" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/deep-rl", hubAnchor: "foundations", hubLabel: "Deep RL → Основы", contextInLesson: "Выбор архитектуры под тип наблюдений", contextInHub: "Архитектурные решения (Урок 3.7)" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/fca-rl", hubAnchor: "fca-architecture", hubLabel: "FCA → Архитектура", contextInLesson: "FCA для выбора архитектуры по свойствам задачи", contextInHub: "FCA-анализ архитектур (Урок 3.7)" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/fca-rl", hubAnchor: "fca-basics", hubLabel: "FCA → Основы", contextInLesson: "Формальные понятия для классификации архитектур", contextInHub: "Основы FCA (Урок 3.7)" },

  // ═══ Связи с учебным пособием ═══
  // Источник пар — math-textbook/_meta/crosslinks.md §3 «Раздел → уроки».
  // hubPath/hubAnchor ведут в краткую версию хаба, textbookRoute — в полную лекцию.

  // ── Урок 1-1 → учебник ──
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "2-бесконечные-ряды-и-их-сходимость", hubLabel: "Математика → Бесконечные ряды", contextInLesson: "Почему сумма бесконечного числа наград — конечное число", contextInHub: "Введение в RL (Урок 1.1)", textbookRoute: "/math-rl/textbook/part-1/02-infinite-series" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "3-пределы-и-ряды-в-контексте-обучения-с-подкреплением", hubLabel: "Математика → Пределы в RL", contextInLesson: "Где именно в цикле «агент — среда» возникает бесконечность", contextInHub: "Введение в RL (Урок 1.1)", textbookRoute: "/math-rl/textbook/part-1/03-limits-in-rl" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "6-дисконтирование-в-rl-и-его-влияние", hubLabel: "Математика → Дисконтирование", contextInLesson: "Что означает γ и как он задаёт горизонт планирования", contextInHub: "Введение в RL (Урок 1.1)", textbookRoute: "/math-rl/textbook/part-1/06-discounting-in-rl" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "3-марковские-процессы", hubLabel: "Математика → Марковские процессы", contextInLesson: "Марковское свойство: почему хватает текущего состояния", contextInHub: "Введение в RL (Урок 1.1)", textbookRoute: "/math-rl/textbook/part-4/03-markov-processes" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "4-функции-ценности-и-уравнения-беллмана", hubLabel: "Математика → Функции ценности", contextInLesson: "Строгие определения V и Q, которыми пользуется весь курс", contextInHub: "Введение в RL (Урок 1.1)", textbookRoute: "/math-rl/textbook/part-4/04-value-functions-bellman" },
  { lessonId: "1-1", lessonPath: "/courses/1-1", lessonTitle: "Что такое RL?", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-4", hubLabel: "Математика → Возврат и политики", contextInLesson: "Возврат, политика и ценность — три объекта, вокруг которых всё построено", contextInHub: "Введение в RL (Урок 1.1)", textbookRoute: "/math-rl/textbook/part-6/04-return-policy-value" },

  // ── Урок 1-2 → учебник ──
  { lessonId: "1-2", lessonPath: "/courses/1-2", lessonTitle: "Установка окружения", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-10", hubLabel: "Математика → Мост к Unity ML-Agents", contextInLesson: "Что означает каждое поле в .yaml-конфиге, который вы только что поставили", contextInHub: "Настройка среды обучения (Урок 1.2)", textbookRoute: "/math-rl/textbook/part-6/10-unity-ml-agents-bridge" },

  // ── Урок 1-3 → учебник ──
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "1-теоретические-основы-предел-последовательности", hubLabel: "Математика → Предел последовательности", contextInLesson: "Определение предела — на нём держится сходимость итерации ценности", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-1/01-sequence-limit" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "5-итерация-ценности-сходимость-на-практике", hubLabel: "Математика → Итерация ценности", contextInLesson: "Почему итерация сходится и когда её законно останавливать", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-1/05-value-iteration" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "7-примеры-аналогии-и-задачи", hubLabel: "Математика → Задачи на пределы", contextInLesson: "Разбор MDP с двумя состояниями на числах", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-1/07-examples-and-tasks" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "8-интерактивные-визуализации-сходимости", hubLabel: "Математика → Визуализации сходимости", contextInLesson: "Как выглядит сходимость итерации ценности на графике", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-1/08-convergence-visualizations" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "8b-практические-задачи-пределы-и-сходимость", hubLabel: "Математика → Практика: пределы", contextInLesson: "Задачи на сходимость с ответами", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-1/09-practice-limits" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "3-марковские-процессы", hubLabel: "Математика → Марковские процессы", contextInLesson: "Цепи Маркова и переход к MDP", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-4/03-markov-processes" },
  { lessonId: "1-3", lessonPath: "/courses/1-3", lessonTitle: "MDP и уравнения Беллмана", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "4-функции-ценности-и-уравнения-беллмана", hubLabel: "Математика → Функции ценности", contextInLesson: "Четыре уравнения Беллмана в одном месте", contextInHub: "MDP на практике (Урок 1.3)", textbookRoute: "/math-rl/textbook/part-4/04-value-functions-bellman" },

  // ── Урок 1-4 → учебник ──
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "4-уравнения-беллмана-и-дисконтирование", hubLabel: "Математика → Беллман и дисконтирование", contextInLesson: "Откуда берётся рекурсия, которую обновляет Q-таблица", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-1/04-bellman-and-discounting" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "5-итерация-ценности-сходимость-на-практике", hubLabel: "Математика → Итерация ценности", contextInLesson: "Критерий остановки: сколько проходов достаточно", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-1/05-value-iteration" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "7-примеры-аналогии-и-задачи", hubLabel: "Математика → Задачи на пределы", contextInLesson: "Сходимость Q-обучения на числовом примере", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-1/07-examples-and-tasks" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "4-функции-ценности-и-уравнения-беллмана", hubLabel: "Математика → Функции ценности", contextInLesson: "Связь V и Q, из которой выводится жадная политика", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-4/04-value-functions-bellman" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "5-алгоритмы-rl", hubLabel: "Математика → Алгоритмы RL", contextInLesson: "Место табличного Q-обучения среди остальных методов", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-4/05-rl-algorithms" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-4", hubLabel: "Математика → Возврат и политики", contextInLesson: "Что именно оценивает Q-таблица", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-6/04-return-policy-value" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-5", hubLabel: "Математика → Уравнения Беллмана", contextInLesson: "Полный вывод уравнения, по которому идёт обновление", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-6/05-bellman-equations" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-6", hubLabel: "Математика → Model-Free RL", contextInLesson: "Чем Q-learning отличается от SARSA и от динамического программирования", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-6/06-model-free-rl" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-7", hubLabel: "Математика → Следы пригодности", contextInLesson: "Как ускорить распространение награды по эпизоду", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-6/07-eligibility-traces" },
  { lessonId: "1-4", lessonPath: "/courses/1-4", lessonTitle: "Q-Learning: табличный метод", lessonLevel: 1, hubPath: "/math-rl/calculus", hubAnchor: "4-применение-в-rl-policy-gradient", hubLabel: "Математика → TD-ошибка как градиент", contextInLesson: "TD-ошибка: тот же объект, но со стороны оптимизации", contextInHub: "Табличный Q-Learning (Урок 1.4)", textbookRoute: "/math-rl/textbook/part-2/04-policy-gradient-application" },

  // ── Урок 1-5 → учебник ──
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "6-практические-примеры-python", hubLabel: "Математика → Примеры на Python", contextInLesson: "Оценка политики и симуляции на numpy — тот же код, что в уроке", contextInHub: "Первый агент на CartPole (Урок 1.5)", textbookRoute: "/math-rl/textbook/part-4/06-python-examples" },
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-8", hubLabel: "Математика → Аппроксимация функций", contextInLesson: "Почему таблицу приходится заменять сетью", contextInHub: "Первый агент на CartPole (Урок 1.5)", textbookRoute: "/math-rl/textbook/part-6/08-function-approximation" },
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/math-rl/module-6", hubAnchor: "1-1-основные-понятия", hubLabel: "Математика → Понятия Deep RL", contextInLesson: "Словарь Deep RL: что есть что в вашем цикле обучения", contextInHub: "Первый агент на CartPole (Урок 1.5)", textbookRoute: "/math-rl/textbook/part-7/01-core-concepts" },
  { lessonId: "1-5", lessonPath: "/courses/1-5", lessonTitle: "CartPole — твой первый RL-агент", lessonLevel: 1, hubPath: "/math-rl/module-6", hubAnchor: "1-2-обзор-алгоритмов-rl", hubLabel: "Математика → Обзор алгоритмов", contextInLesson: "Куда двигаться после CartPole", contextInHub: "Первый агент на CartPole (Урок 1.5)", textbookRoute: "/math-rl/textbook/part-7/02-algorithms-overview" },

  // ── Урок 1-6 → учебник ──
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-1", hubAnchor: "5-итерация-ценности-сходимость-на-практике", hubLabel: "Математика → Итерация ценности", contextInLesson: "Сходимость и критерий остановки — то же и для DQN", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-1/05-value-iteration" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/calculus", hubAnchor: "3-градиентный-спуск-и-оптимизация", hubLabel: "Математика → Градиентный спуск", contextInLesson: "Что делает optimizer.step() с параметрами Q-сети", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-2/03-gradient-descent" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/calculus", hubAnchor: "4-применение-в-rl-policy-gradient", hubLabel: "Математика → TD-ошибка как градиент", contextInLesson: "TD-ошибка как стохастический градиент функции потерь", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-2/04-policy-gradient-application" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "4-функции-ценности-и-уравнения-беллмана", hubLabel: "Математика → Функции ценности", contextInLesson: "Целевое значение y = r + γ·max Q и откуда оно", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-4/04-value-functions-bellman" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-3", hubAnchor: "5-алгоритмы-rl", hubLabel: "Математика → Алгоритмы RL", contextInLesson: "DQN среди value-based методов", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-4/05-rl-algorithms" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-6", hubLabel: "Математика → Model-Free RL", contextInLesson: "Почему DQN обучается без модели среды", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-6/06-model-free-rl" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-7", hubLabel: "Математика → Следы пригодности", contextInLesson: "n-шаговые возвраты как альтернатива одношаговой цели", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-6/07-eligibility-traces" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-8", hubLabel: "Математика → Аппроксимация функций", contextInLesson: "Deadly triad: почему нужны replay buffer и target network", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-6/08-function-approximation" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-6", hubAnchor: "1-1-основные-понятия", hubLabel: "Математика → Понятия Deep RL", contextInLesson: "Терминология Deep RL к вашей реализации", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-7/01-core-concepts" },
  { lessonId: "1-6", lessonPath: "/courses/1-6", lessonTitle: "DQN с нуля на PyTorch", lessonLevel: 1, hubPath: "/math-rl/module-6", hubAnchor: "1-2-обзор-алгоритмов-rl", hubLabel: "Математика → Обзор алгоритмов", contextInLesson: "Rainbow и другие улучшения DQN", contextInHub: "Реализация DQN (Урок 1.6)", textbookRoute: "/math-rl/textbook/part-7/02-algorithms-overview" },

  // ── Урок 1-7 → учебник ──
  { lessonId: "1-7", lessonPath: "/courses/1-7", lessonTitle: "Exploration vs Exploitation", lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-2", hubLabel: "Математика → Многорукие бандиты", contextInLesson: "ε-жадная стратегия и UCB со строгими оценками сожаления", contextInHub: "Стратегии исследования (Урок 1.7)", textbookRoute: "/math-rl/textbook/part-6/02-multi-armed-bandits" },

  // ── Урок 2-1 → учебник ──
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/calculus", hubAnchor: "1-производные-и-дифференцирование", hubLabel: "Математика → Производные", contextInLesson: "Производная как скорость изменения — язык всей оптимизации", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-2/01-derivatives" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/calculus", hubAnchor: "2-частные-производные-и-градиент", hubLabel: "Математика → Частные производные и градиент", contextInLesson: "Градиент по вектору параметров: что мы дифференцируем", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-2/02-partial-derivatives-gradient" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/calculus", hubAnchor: "4-применение-в-rl-policy-gradient", hubLabel: "Математика → Применение в RL", contextInLesson: "Теорема о градиенте политики в компактной записи", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-2/04-policy-gradient-application" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/calculus", hubAnchor: "5-весь-раздел-в-одной-картине", hubLabel: "Математика → Весь раздел в одной картине", contextInLesson: "Как связаны производная, градиент и обновление политики", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-2/05-big-picture" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-4", hubAnchor: "лекция-1-основы-rl-и-оптимизация-политики", hubLabel: "Математика → Основы оптимизации политики", contextInLesson: "Целевая функция J(θ): что именно максимизируем", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-5/01-policy-optimization-basics" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-1", hubLabel: "Математика → Вероятностный фундамент", contextInLesson: "Математическое ожидание, по которому берётся градиент", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-6/01-probability-foundation" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-9", hubLabel: "Математика → Policy Gradients", contextInLesson: "REINFORCE, базис и переход к Actor-Critic", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-6/09-policy-gradients" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-6", hubAnchor: "2-1-математический-анализ", hubLabel: "Математика → Математический анализ", contextInLesson: "Правила дифференцирования, нужные для вывода", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-7/03-calculus" },
  { lessonId: "2-1", lessonPath: "/courses/2-1", lessonTitle: "Policy Gradient и REINFORCE", lessonLevel: 2, hubPath: "/math-rl/module-6", hubAnchor: "2-2-теория-вероятностей-и-статистика", hubLabel: "Математика → Вероятность и статистика", contextInLesson: "Дисперсия оценки градиента и способы её снизить", contextInHub: "REINFORCE в коде (Урок 2.1)", textbookRoute: "/math-rl/textbook/part-7/04-probability-statistics" },

  // ── Урок 2-2 → учебник ──
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/calculus", hubAnchor: "4-применение-в-rl-policy-gradient", hubLabel: "Математика → Применение в RL", contextInLesson: "Advantage и его роль в суррогатной функции", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-2/04-policy-gradient-application" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-3", hubAnchor: "5-алгоритмы-rl", hubLabel: "Математика → Алгоритмы RL", contextInLesson: "PPO среди policy-based методов", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-4/05-rl-algorithms" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-4", hubAnchor: "лекция-1-основы-rl-и-оптимизация-политики", hubLabel: "Математика → Основы оптимизации политики", contextInLesson: "Что оптимизирует PPO и почему шаг ограничивают", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-5/01-policy-optimization-basics" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-4", hubAnchor: "лекция-2-вывод-градиента-политики", hubLabel: "Математика → Вывод градиента политики", contextInLesson: "Полный вывод от J(θ) до формулы REINFORCE", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-5/02-policy-gradient-derivation" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-4", hubAnchor: "лекция-4-proximal-policy-optimization-ppo", hubLabel: "Математика → PPO", contextInLesson: "Клиппинг, GAE и смысл каждого гиперпараметра", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-5/04-ppo" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-7", hubLabel: "Математика → Следы пригодности", contextInLesson: "λ в GAE — тот же параметр, что в TD(λ)", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-6/07-eligibility-traces" },
  { lessonId: "2-2", lessonPath: "/courses/2-2", lessonTitle: "PPO — реализация с нуля", lessonLevel: 2, hubPath: "/math-rl/module-6", hubAnchor: "1-2-обзор-алгоритмов-rl", hubLabel: "Математика → Обзор алгоритмов", contextInLesson: "Место PPO среди современных алгоритмов", contextInHub: "Реализация PPO (Урок 2.2)", textbookRoute: "/math-rl/textbook/part-7/02-algorithms-overview" },

  // ── Урок 2-3 → учебник ──
  { lessonId: "2-3", lessonPath: "/courses/2-3", lessonTitle: "Непрерывные действия и Actor-Critic", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-9", hubLabel: "Математика → Policy Gradients", contextInLesson: "Гауссова политика и архитектура «актор — критик»", contextInHub: "Continuous Actor-Critic (Урок 2.3)", textbookRoute: "/math-rl/textbook/part-6/09-policy-gradients" },

  // ── Урок 2-4 → учебник ──
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "2-бесконечные-ряды-и-их-сходимость", hubLabel: "Математика → Бесконечные ряды", contextInLesson: "Почему добавка к награде не ломает сходимость возврата", contextInHub: "Проектирование награды (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-1/02-infinite-series" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "3-пределы-и-ряды-в-контексте-обучения-с-подкреплением", hubLabel: "Математика → Пределы в RL", contextInLesson: "Что происходит с возвратом при изменении функции награды", contextInHub: "Проектирование награды (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-1/03-limits-in-rl" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "4-уравнения-беллмана-и-дисконтирование", hubLabel: "Математика → Беллман и дисконтирование", contextInLesson: "Потенциальное shaping и инвариантность оптимальной политики", contextInHub: "Проектирование награды (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-1/04-bellman-and-discounting" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "7-примеры-аналогии-и-задачи", hubLabel: "Математика → Задачи на пределы", contextInLesson: "Числовые примеры влияния γ на поведение агента", contextInHub: "Проектирование награды (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-1/07-examples-and-tasks" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "8b-практические-задачи-пределы-и-сходимость", hubLabel: "Математика → Практика: пределы", contextInLesson: "Задачи на эффективный горизонт", contextInHub: "Проектирование награды (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-1/09-practice-limits" },
  { lessonId: "2-4", lessonPath: "/courses/2-4", lessonTitle: "Reward Shaping", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-4", hubLabel: "Математика → Возврат и политики", contextInLesson: "Как форма награды меняет ранжирование политик", contextInHub: "Проектирование награды (Урок 2.4)", textbookRoute: "/math-rl/textbook/part-6/04-return-policy-value" },

  // ── Урок 2-5 → учебник ──
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "введение", hubLabel: "Математика → Введение в часть I", contextInLesson: "Зачем вообще нужен предел, если обучение всегда обрывают", contextInHub: "Параллельные среды (Урок 2.5)", textbookRoute: "/math-rl/textbook/part-1/00-introduction" },
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "1-теоретические-основы-предел-последовательности", hubLabel: "Математика → Предел последовательности", contextInLesson: "Что значит «обучение сошлось» формально", contextInHub: "Параллельные среды (Урок 2.5)", textbookRoute: "/math-rl/textbook/part-1/01-sequence-limit" },
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "2-бесконечные-ряды-и-их-сходимость", hubLabel: "Математика → Бесконечные ряды", contextInLesson: "Сходимость суммы наград не зависит от числа сред", contextInHub: "Параллельные среды (Урок 2.5)", textbookRoute: "/math-rl/textbook/part-1/02-infinite-series" },
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "5-итерация-ценности-сходимость-на-практике", hubLabel: "Математика → Итерация ценности", contextInLesson: "Скорость сходимости: что даёт больше сред, а что — больше шагов", contextInHub: "Параллельные среды (Урок 2.5)", textbookRoute: "/math-rl/textbook/part-1/05-value-iteration" },
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "8-интерактивные-визуализации-сходимости", hubLabel: "Математика → Визуализации сходимости", contextInLesson: "Как отличить медленную сходимость от расходимости", contextInHub: "Параллельные среды (Урок 2.5)", textbookRoute: "/math-rl/textbook/part-1/08-convergence-visualizations" },
  { lessonId: "2-5", lessonPath: "/courses/2-5", lessonTitle: "Параллельные среды", lessonLevel: 2, hubPath: "/math-rl/module-2", hubAnchor: "4-собственные-значения-и-собственные-векторы", hubLabel: "Математика → Собственные значения", contextInLesson: "Коэффициент сжатия и скорость сходимости", contextInHub: "Параллельные среды (Урок 2.5)", textbookRoute: "/math-rl/textbook/part-3/04-eigenvalues" },

  // ── Урок 2-6 → учебник ──
  { lessonId: "2-6", lessonPath: "/courses/2-6", lessonTitle: "TensorBoard и W&B", lessonLevel: 2, hubPath: "/math-rl/module-1", hubAnchor: "8-интерактивные-визуализации-сходимости", hubLabel: "Математика → Визуализации сходимости", contextInLesson: "Как читать кривую ошибки: сходится, стоит или расходится", contextInHub: "Чтение графиков обучения (Урок 2.6)", textbookRoute: "/math-rl/textbook/part-1/08-convergence-visualizations" },
  { lessonId: "2-6", lessonPath: "/courses/2-6", lessonTitle: "TensorBoard и W&B", lessonLevel: 2, hubPath: "/math-rl/module-3", hubAnchor: "2-статистика", hubLabel: "Математика → Статистика", contextInLesson: "Среднее, дисперсия и доверительные интервалы на графиках обучения", contextInHub: "Чтение графиков обучения (Урок 2.6)", textbookRoute: "/math-rl/textbook/part-4/02-statistics" },
  { lessonId: "2-6", lessonPath: "/courses/2-6", lessonTitle: "TensorBoard и W&B", lessonLevel: 2, hubPath: "/math-rl/module-6", hubAnchor: "2-2-теория-вероятностей-и-статистика", hubLabel: "Математика → Вероятность и статистика", contextInLesson: "Сравнение прогонов: когда разница значима", contextInHub: "Чтение графиков обучения (Урок 2.6)", textbookRoute: "/math-rl/textbook/part-7/04-probability-statistics" },

  // ── Урок 3-1 → учебник ──
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/math-rl/module-3", hubAnchor: "5-алгоритмы-rl", hubLabel: "Математика → Алгоритмы RL", contextInLesson: "SAC среди off-policy методов", contextInHub: "Реализация SAC (Урок 3.1)", textbookRoute: "/math-rl/textbook/part-4/05-rl-algorithms" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/math-rl/module-4", hubAnchor: "лекция-4-proximal-policy-optimization-ppo", hubLabel: "Математика → PPO", contextInLesson: "С чем сравнивать SAC: on-policy против off-policy", contextInHub: "Реализация SAC (Урок 3.1)", textbookRoute: "/math-rl/textbook/part-5/04-ppo" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/math-rl/module-5", hubAnchor: "глава-10", hubLabel: "Математика → Мост к Unity ML-Agents", contextInLesson: "Поля SAC-конфига и их математический смысл", contextInHub: "Реализация SAC (Урок 3.1)", textbookRoute: "/math-rl/textbook/part-6/10-unity-ml-agents-bridge" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/math-rl/module-6", hubAnchor: "1-2-обзор-алгоритмов-rl", hubLabel: "Математика → Обзор алгоритмов", contextInLesson: "Семейство максэнтропийных методов", contextInHub: "Реализация SAC (Урок 3.1)", textbookRoute: "/math-rl/textbook/part-7/02-algorithms-overview" },
  { lessonId: "3-1", lessonPath: "/courses/3-1", lessonTitle: "SAC — Soft Actor-Critic", lessonLevel: 3, hubPath: "/math-rl/module-6", hubAnchor: "2-3-дифференциальные-уравнения", hubLabel: "Математика → Дифференциальные уравнения", contextInLesson: "Непрерывное управление и динамика системы", contextInHub: "Реализация SAC (Урок 3.1)", textbookRoute: "/math-rl/textbook/part-7/05-differential-equations" },

  // ── Урок 3-4 → учебник ──
  { lessonId: "3-4", lessonPath: "/courses/3-4", lessonTitle: "Имитационное обучение (GAIL)", lessonLevel: 3, hubPath: "/math-rl/module-6", hubAnchor: "2-2-теория-вероятностей-и-статистика", hubLabel: "Математика → Вероятность и статистика", contextInLesson: "Расхождение распределений: чем меряют похожесть политики на демонстрации", contextInHub: "GAIL на практике (Урок 3.4)", textbookRoute: "/math-rl/textbook/part-7/04-probability-statistics" },

  // ── Урок 3-6 → учебник ──
  { lessonId: "3-6", lessonPath: "/courses/3-6", lessonTitle: "Оптимизация гиперпараметров", lessonLevel: 3, hubPath: "/math-rl/module-2", hubAnchor: "6-дополнительные-темы", hubLabel: "Математика → Дополнительные темы", contextInLesson: "Обусловленность задачи: почему один learning rate не подходит всем", contextInHub: "Подбор гиперпараметров (Урок 3.6)", textbookRoute: "/math-rl/textbook/part-3/06-advanced-topics" },
  { lessonId: "3-6", lessonPath: "/courses/3-6", lessonTitle: "Оптимизация гиперпараметров", lessonLevel: 3, hubPath: "/math-rl/module-4", hubAnchor: "лекция-4-proximal-policy-optimization-ppo", hubLabel: "Математика → PPO", contextInLesson: "Что физически меняет каждый гиперпараметр PPO", contextInHub: "Подбор гиперпараметров (Урок 3.6)", textbookRoute: "/math-rl/textbook/part-5/04-ppo" },
  { lessonId: "3-6", lessonPath: "/courses/3-6", lessonTitle: "Оптимизация гиперпараметров", lessonLevel: 3, hubPath: "/math-rl/module-6", hubAnchor: "2-1-математический-анализ", hubLabel: "Математика → Математический анализ", contextInLesson: "Экстремумы и условия оптимальности при поиске", contextInHub: "Подбор гиперпараметров (Урок 3.6)", textbookRoute: "/math-rl/textbook/part-7/03-calculus" },

  // ── Урок 3-7 → учебник ──
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/math-rl/module-2", hubAnchor: "2-матрицы", hubLabel: "Математика → Матрицы", contextInLesson: "Слой сети как матричное умножение", contextInHub: "Выбор архитектуры сети (Урок 3.7)", textbookRoute: "/math-rl/textbook/part-3/02-matrices" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/math-rl/module-2", hubAnchor: "3-скалярное-произведение", hubLabel: "Математика → Скалярное произведение", contextInLesson: "Скалярное произведение внутри свёртки и внимания", contextInHub: "Выбор архитектуры сети (Урок 3.7)", textbookRoute: "/math-rl/textbook/part-3/03-dot-product" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/math-rl/module-2", hubAnchor: "4-собственные-значения-и-собственные-векторы", hubLabel: "Математика → Собственные значения", contextInLesson: "Спектр весов и устойчивость обучения", contextInHub: "Выбор архитектуры сети (Урок 3.7)", textbookRoute: "/math-rl/textbook/part-3/04-eigenvalues" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/math-rl/module-2", hubAnchor: "5-сингулярное-разложение-svd", hubLabel: "Математика → Сингулярное разложение", contextInLesson: "SVD и сжатие представлений", contextInHub: "Выбор архитектуры сети (Урок 3.7)", textbookRoute: "/math-rl/textbook/part-3/05-svd" },
  { lessonId: "3-7", lessonPath: "/courses/3-7", lessonTitle: "Архитектуры нейросетей", lessonLevel: 3, hubPath: "/math-rl/module-2", hubAnchor: "6-дополнительные-темы", hubLabel: "Математика → Дополнительные темы", contextInLesson: "Ортогональная инициализация и смена базиса", contextInHub: "Выбор архитектуры сети (Урок 3.7)", textbookRoute: "/math-rl/textbook/part-3/06-advanced-topics" },

  // ── Урок project-1 → учебник ──
  { lessonId: "project-1", lessonPath: "/courses/project-1", lessonTitle: 'Проект-1: "Баланс в 3D"', lessonLevel: 1, hubPath: "/math-rl/module-5", hubAnchor: "глава-10", hubLabel: "Математика → Мост к Unity ML-Agents", contextInLesson: "Event-функции Unity и элементы MDP — соответствие один в один", contextInHub: "Проект «Баланс в 3D»", textbookRoute: "/math-rl/textbook/part-6/10-unity-ml-agents-bridge" },

  // ── Урок project-2 → учебник ──
  { lessonId: "project-2", lessonPath: "/courses/project-2", lessonTitle: "Проект: 3D-охотник", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-10", hubLabel: "Математика → Мост к Unity ML-Agents", contextInLesson: "Настройка наблюдений и наград в терминах MDP", contextInHub: "Проект «3D-охотник»", textbookRoute: "/math-rl/textbook/part-6/10-unity-ml-agents-bridge" },

  // ── Урок project-3 → учебник ──
  { lessonId: "project-3", lessonPath: "/courses/project-3", lessonTitle: "Проект: Гоночный агент", lessonLevel: 2, hubPath: "/math-rl/module-4", hubAnchor: "лекция-4-proximal-policy-optimization-ppo", hubLabel: "Математика → PPO", contextInLesson: "Гиперпараметры PPO для непрерывного управления", contextInHub: "Проект «Гоночный агент»", textbookRoute: "/math-rl/textbook/part-5/04-ppo" },
  { lessonId: "project-3", lessonPath: "/courses/project-3", lessonTitle: "Проект: Гоночный агент", lessonLevel: 2, hubPath: "/math-rl/module-5", hubAnchor: "глава-10", hubLabel: "Математика → Мост к Unity ML-Agents", contextInLesson: "Конфиг обучения гоночного агента по полям", contextInHub: "Проект «Гоночный агент»", textbookRoute: "/math-rl/textbook/part-6/10-unity-ml-agents-bridge" },

];

/** Get all crosslinks for a specific lesson */
export function getLinksForLesson(lessonId: string): CrossLink[] {
  return CROSSLINKS.filter((link) => link.lessonId === lessonId);
}

/** Get all crosslinks pointing to a specific hub (optionally filtered by anchor) */
export function getLinksForHub(hubPath: string, anchor?: string): CrossLink[] {
  return CROSSLINKS.filter((link) => {
    if (link.hubPath !== hubPath) return false;
    if (anchor !== undefined && link.hubAnchor !== anchor) return false;
    return true;
  });
}

/** Уроки, из которых ведёт ссылка в конкретную лекцию пособия. */
export function getLinksForTextbook(textbookRoute: string): CrossLink[] {
  return CROSSLINKS.filter((link) => link.textbookRoute === textbookRoute);
}

/** Check if a lesson level is free (level 1) */
export function isLessonFree(lessonLevel: number): boolean {
  return lessonLevel === 1;
}
