// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/list-lessons.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";

// src/content/lessonContextLinks.ts
var LESSON_CONTEXT_LINKS = {
  /* ── Stage 1 ── */
  "basics-rl": [
    {
      hubId: "math-rl",
      placement: "after-intro",
      title: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 \u0437\u0430 MDP",
      whyThisNow: "\u0427\u0442\u043E\u0431\u044B \u043F\u043E\u043D\u044F\u0442\u044C \u043D\u0430\u0433\u0440\u0430\u0434\u044B \u0438 \u043F\u0435\u0440\u0435\u0445\u043E\u0434\u044B, \u043F\u043E\u043B\u0435\u0437\u043D\u043E \u0437\u043D\u0430\u0442\u044C \u043E\u0441\u043D\u043E\u0432\u044B \u0432\u0435\u0440\u043E\u044F\u0442\u043D\u043E\u0441\u0442\u0435\u0439.",
      ctaLabel: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u043C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0443",
      isPrimary: false
    },
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "\u0412\u0432\u0435\u0434\u0435\u043D\u0438\u0435 \u0432 Deep RL",
      whyThisNow: "\u0411\u0430\u0437\u043E\u0432\u044B\u0435 \u043A\u043E\u043D\u0446\u0435\u043F\u0446\u0438\u0438 RL \u2014 \u0444\u0443\u043D\u0434\u0430\u043C\u0435\u043D\u0442 \u0434\u043B\u044F \u0432\u0441\u0435\u0445 \u043F\u043E\u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0438\u0445 \u0430\u043B\u0433\u043E\u0440\u0438\u0442\u043C\u043E\u0432.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "setup-pytorch-unity": [
    {
      hubId: "pytorch",
      placement: "after-core-explanation",
      title: "\u0428\u043F\u0430\u0440\u0433\u0430\u043B\u043A\u0430 PyTorch",
      whyThisNow: "\u0417\u0434\u0435\u0441\u044C \u043C\u044B \u0443\u0441\u0442\u0430\u043D\u0430\u0432\u043B\u0438\u0432\u0430\u0435\u043C PyTorch \u2014 \u0437\u0430\u0433\u043B\u044F\u043D\u0438\u0442\u0435 \u0432 \u0445\u0430\u0431 \u0437\u0430 \u0441\u043F\u0440\u0430\u0432\u043A\u043E\u0439 \u043F\u043E \u0442\u0435\u043D\u0437\u043E\u0440\u0430\u043C.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 Unity ML-Agents",
      whyThisNow: "\u041F\u0430\u0440\u0430\u043B\u043B\u0435\u043B\u044C\u043D\u043E \u043D\u0430\u0441\u0442\u0440\u0430\u0438\u0432\u0430\u0435\u043C Unity \u2014 \u043F\u043E\u0434\u0440\u043E\u0431\u043D\u043E\u0441\u0442\u0438 \u0432 \u0445\u0430\u0431\u0435.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "cartpole": [
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "\u041D\u0435\u0439\u0440\u043E\u0441\u0435\u0442\u044C \u0432 PyTorch",
      whyThisNow: "CartPole \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0435\u0442 \u043F\u0440\u043E\u0441\u0442\u0443\u044E \u043D\u0435\u0439\u0440\u043E\u0441\u0435\u0442\u044C \u2014 \u043F\u043E\u0432\u0442\u043E\u0440\u0438\u0442\u0435 \u043E\u0441\u043D\u043E\u0432\u044B nn.Module.",
      ctaLabel: "\u041F\u043E\u0432\u0442\u043E\u0440\u0438\u0442\u044C PyTorch",
      isPrimary: false
    },
    {
      hubId: "project",
      placement: "lesson-end",
      title: "\u041F\u0440\u043E\u0435\u043A\u0442: CartPole",
      whyThisNow: "\u0417\u0430\u043A\u0440\u0435\u043F\u0438\u0442\u0435 \u0437\u043D\u0430\u043D\u0438\u044F \u0432 \u0441\u0430\u043C\u043E\u0441\u0442\u043E\u044F\u0442\u0435\u043B\u044C\u043D\u043E\u043C \u043F\u0440\u043E\u0435\u043A\u0442\u0435.",
      ctaLabel: "\u041A \u043F\u0440\u043E\u0435\u043A\u0442\u0443",
      isPrimary: true
    }
  ],
  "basic-dqn": [
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "\u0422\u0435\u043E\u0440\u0438\u044F DQN",
      whyThisNow: "\u0413\u043B\u0443\u0431\u0436\u0435 \u0440\u0430\u0437\u0431\u0435\u0440\u0451\u043C experience replay \u0438 target network.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "math-rl",
      placement: "after-intro",
      title: "\u0423\u0440\u0430\u0432\u043D\u0435\u043D\u0438\u0435 \u0411\u0435\u043B\u043B\u043C\u0430\u043D\u0430",
      whyThisNow: "DQN \u043E\u043F\u0438\u0440\u0430\u0435\u0442\u0441\u044F \u043D\u0430 \u0443\u0440\u0430\u0432\u043D\u0435\u043D\u0438\u0435 \u0411\u0435\u043B\u043B\u043C\u0430\u043D\u0430 \u2014 \u043E\u0441\u0432\u0435\u0436\u0438\u0442\u0435 \u0444\u043E\u0440\u043C\u0443\u043B\u0443.",
      ctaLabel: "\u041A \u043C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0435",
      isPrimary: false
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "nn.Module \u0438 \u043E\u043F\u0442\u0438\u043C\u0438\u0437\u0430\u0442\u043E\u0440",
      whyThisNow: "DQN \u0441\u0442\u0440\u043E\u0438\u0442\u0441\u044F \u043D\u0430 nn.Module \u2014 \u043F\u043E\u0432\u0442\u043E\u0440\u0438\u0442\u0435 \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u0443 \u0441\u0435\u0442\u0438.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "mdp": [
    {
      hubId: "math-rl",
      placement: "after-core-explanation",
      title: "\u0424\u043E\u0440\u043C\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F MDP",
      whyThisNow: "\u041C\u0430\u0440\u043A\u043E\u0432\u0441\u043A\u043E\u0435 \u0441\u0432\u043E\u0439\u0441\u0442\u0432\u043E, \u043F\u0435\u0440\u0435\u0445\u043E\u0434\u044B, \u0434\u0438\u0441\u043A\u043E\u043D\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u2014 \u0432\u0441\u044F \u043C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 \u0437\u0434\u0435\u0441\u044C.",
      ctaLabel: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 RL",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-intro",
      title: "MDP \u0432 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0435 RL",
      whyThisNow: "MDP \u2014 \u043E\u0441\u043D\u043E\u0432\u0430 \u0432\u0441\u0435\u0445 \u0430\u043B\u0433\u043E\u0440\u0438\u0442\u043C\u043E\u0432 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044F \u0441 \u043F\u043E\u0434\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u0438\u0435\u043C.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "q-learning-tabular": [
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "\u041E\u0442 \u0442\u0430\u0431\u043B\u0438\u0446\u044B \u043A \u043D\u0435\u0439\u0440\u043E\u0441\u0435\u0442\u0438",
      whyThisNow: "\u0422\u0430\u0431\u043B\u0438\u0447\u043D\u044B\u0439 Q-Learning \u2014 \u043F\u0440\u0435\u0434\u0448\u0435\u0441\u0442\u0432\u0435\u043D\u043D\u0438\u043A DQN \u0438 \u0432\u0441\u0435\u0445 value-based \u043C\u0435\u0442\u043E\u0434\u043E\u0432.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "math-rl",
      placement: "after-intro",
      title: "Q-\u0444\u0443\u043D\u043A\u0446\u0438\u044F \u0438 \u0441\u0445\u043E\u0434\u0438\u043C\u043E\u0441\u0442\u044C",
      whyThisNow: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0435 \u0433\u0430\u0440\u0430\u043D\u0442\u0438\u0438 \u0441\u0445\u043E\u0434\u0438\u043C\u043E\u0441\u0442\u0438 Q-Learning.",
      ctaLabel: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430",
      isPrimary: false
    }
  ],
  "exploration-exploitation": [
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "\u0421\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u0438 \u0438\u0441\u0441\u043B\u0435\u0434\u043E\u0432\u0430\u043D\u0438\u044F",
      whyThisNow: "\u03B5-greedy, UCB, Boltzmann \u2014 \u0441\u0440\u0430\u0432\u043D\u0435\u043D\u0438\u0435 \u043F\u043E\u0434\u0445\u043E\u0434\u043E\u0432.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "math-rl",
      placement: "after-intro",
      title: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 exploration",
      whyThisNow: "\u0412\u0435\u0440\u043E\u044F\u0442\u043D\u043E\u0441\u0442\u043D\u044B\u0435 \u043E\u0441\u043D\u043E\u0432\u044B \u0441\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u0439 \u0438\u0441\u0441\u043B\u0435\u0434\u043E\u0432\u0430\u043D\u0438\u044F.",
      ctaLabel: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430",
      isPrimary: false
    }
  ],
  "project-1": [
    {
      hubId: "project",
      placement: "after-intro",
      title: "\u041F\u0440\u043E\u0435\u043A\u0442: \u0411\u0430\u043B\u0430\u043D\u0441\u0438\u0440\u043E\u0432\u043A\u0430",
      whyThisNow: "\u041F\u0435\u0440\u0432\u044B\u0439 \u0441\u0430\u043C\u043E\u0441\u0442\u043E\u044F\u0442\u0435\u043B\u044C\u043D\u044B\u0439 \u043F\u0440\u043E\u0435\u043A\u0442 \u2014 \u0437\u0430\u043A\u0440\u0435\u043F\u043B\u044F\u0435\u043C \u043E\u0441\u043D\u043E\u0432\u044B.",
      ctaLabel: "\u041F\u0440\u043E\u0435\u043A\u0442\u044B",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "PyTorch \u0432 \u043F\u0440\u043E\u0435\u043A\u0442\u0435",
      whyThisNow: "\u041F\u0440\u0438\u043C\u0435\u043D\u044F\u0435\u043C PyTorch \u0434\u043B\u044F \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044F \u043F\u0435\u0440\u0432\u043E\u0433\u043E \u0430\u0433\u0435\u043D\u0442\u0430.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    },
    {
      hubId: "unity-ml-agents",
      placement: "lesson-end",
      title: "Unity \u0441\u0440\u0435\u0434\u0430",
      whyThisNow: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 \u0441\u0440\u0435\u0434\u044B CartPole \u0432 Unity ML-Agents.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  /* ── Stage 2 ── */
  "policy-gradient": [
    {
      hubId: "math-rl",
      placement: "after-core-explanation",
      title: "\u0413\u0440\u0430\u0434\u0438\u0435\u043D\u0442 \u043F\u043E\u043B\u0438\u0442\u0438\u043A\u0438",
      whyThisNow: "\u0412\u044B\u0432\u043E\u0434 REINFORCE \u0442\u0440\u0435\u0431\u0443\u0435\u0442 \u0437\u043D\u0430\u043D\u0438\u044F \u043B\u043E\u0433\u0430\u0440\u0438\u0444\u043C\u0438\u0447\u0435\u0441\u043A\u0438\u0445 \u043F\u0440\u043E\u0438\u0437\u0432\u043E\u0434\u043D\u044B\u0445.",
      ctaLabel: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-intro",
      title: "Policy-based \u043C\u0435\u0442\u043E\u0434\u044B",
      whyThisNow: "Policy Gradient \u2014 \u0430\u043B\u044C\u0442\u0435\u0440\u043D\u0430\u0442\u0438\u0432\u0430 value-based \u043F\u043E\u0434\u0445\u043E\u0434\u0430\u043C.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "\u0420\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F REINFORCE",
      whyThisNow: "\u041F\u043E\u0441\u0442\u0440\u043E\u0435\u043D\u0438\u0435 \u0433\u0440\u0430\u0444\u0430 \u0432\u044B\u0447\u0438\u0441\u043B\u0435\u043D\u0438\u0439 \u0434\u043B\u044F \u0433\u0440\u0430\u0434\u0438\u0435\u043D\u0442\u0430 \u043F\u043E\u043B\u0438\u0442\u0438\u043A\u0438.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "ppo": [
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "PPO \u0432 \u0434\u0435\u0442\u0430\u043B\u044F\u0445",
      whyThisNow: "Clipping, GAE \u0438 \u0434\u0440\u0443\u0433\u0438\u0435 \u043D\u044E\u0430\u043D\u0441\u044B PPO \u043F\u043E\u0434\u0440\u043E\u0431\u043D\u043E \u0432 \u0445\u0430\u0431\u0435.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "PPO \u043D\u0430 PyTorch",
      whyThisNow: "\u0420\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F clipped objective \u0438 GAE \u0432 PyTorch.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "continuous-actions": [
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "Continuous \u0432 Unity",
      whyThisNow: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 \u043D\u0435\u043F\u0440\u0435\u0440\u044B\u0432\u043D\u044B\u0445 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0439 \u0432 ML-Agents \u043E\u0442\u043B\u0438\u0447\u0430\u0435\u0442\u0441\u044F \u043E\u0442 \u0434\u0438\u0441\u043A\u0440\u0435\u0442\u043D\u044B\u0445.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "Actor-Critic \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u0430",
      whyThisNow: "\u041D\u0435\u043F\u0440\u0435\u0440\u044B\u0432\u043D\u044B\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044F \u0442\u0440\u0435\u0431\u0443\u044E\u0442 Actor-Critic \u043F\u043E\u0434\u0445\u043E\u0434\u0430.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "Gaussian Policy",
      whyThisNow: "\u0420\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F \u043D\u043E\u0440\u043C\u0430\u043B\u044C\u043D\u043E\u0433\u043E \u0440\u0430\u0441\u043F\u0440\u0435\u0434\u0435\u043B\u0435\u043D\u0438\u044F \u0434\u043B\u044F \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0439.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "reward-shaping": [
    {
      hubId: "unity-ml-agents",
      placement: "after-core-explanation",
      title: "\u041D\u0430\u0433\u0440\u0430\u0434\u044B \u0432 Unity",
      whyThisNow: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 \u0444\u0443\u043D\u043A\u0446\u0438\u0438 \u0432\u043E\u0437\u043D\u0430\u0433\u0440\u0430\u0436\u0434\u0435\u043D\u0438\u044F \u0432 Unity-\u0441\u0440\u0435\u0434\u0430\u0445.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-intro",
      title: "Reward Design",
      whyThisNow: "\u041F\u0440\u043E\u0435\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u043D\u0430\u0433\u0440\u0430\u0434 \u2014 \u043A\u043B\u044E\u0447 \u043A \u0443\u0441\u043F\u0435\u0448\u043D\u043E\u043C\u0443 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044E.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "parallel-envs": [
    {
      hubId: "unity-ml-agents",
      placement: "after-core-explanation",
      title: "\u041F\u0430\u0440\u0430\u043B\u043B\u0435\u043B\u0438\u0437\u043C \u0432 Unity",
      whyThisNow: "\u0417\u0430\u043F\u0443\u0441\u043A \u043D\u0435\u0441\u043A\u043E\u043B\u044C\u043A\u0438\u0445 \u044D\u043A\u0437\u0435\u043C\u043F\u043B\u044F\u0440\u043E\u0432 \u0441\u0440\u0435\u0434\u044B \u0432 ML-Agents.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "\u0411\u0430\u0442\u0447\u0435\u0432\u043E\u0435 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u0435",
      whyThisNow: "\u042D\u0444\u0444\u0435\u043A\u0442\u0438\u0432\u043D\u0430\u044F \u043E\u0431\u0440\u0430\u0431\u043E\u0442\u043A\u0430 \u0434\u0430\u043D\u043D\u044B\u0445 \u0438\u0437 \u043F\u0430\u0440\u0430\u043B\u043B\u0435\u043B\u044C\u043D\u044B\u0445 \u0441\u0440\u0435\u0434.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "tensorboard-wandb": [
    {
      hubId: "pytorch",
      placement: "after-core-explanation",
      title: "\u041B\u043E\u0433\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u0432 PyTorch",
      whyThisNow: "\u0418\u043D\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044F TensorBoard \u0438 W&B \u0441 PyTorch-\u043F\u0430\u0439\u043F\u043B\u0430\u0439\u043D\u043E\u043C.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "\u041C\u043E\u043D\u0438\u0442\u043E\u0440\u0438\u043D\u0433 ML-Agents",
      whyThisNow: "\u0412\u0441\u0442\u0440\u043E\u0435\u043D\u043D\u0430\u044F \u043F\u043E\u0434\u0434\u0435\u0440\u0436\u043A\u0430 TensorBoard \u0432 Unity ML-Agents.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "unity-ml-agents-intro": [
    {
      hubId: "unity-ml-agents",
      placement: "after-intro",
      title: "\u041F\u043E\u043B\u043D\u044B\u0439 \u0433\u0430\u0439\u0434 ML-Agents",
      whyThisNow: "\u041F\u043E\u0434\u0440\u043E\u0431\u043D\u0430\u044F \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u0446\u0438\u044F \u043F\u043E \u0432\u0441\u0435\u043C \u043A\u043E\u043C\u043F\u043E\u043D\u0435\u043D\u0442\u0430\u043C \u0444\u0440\u0435\u0439\u043C\u0432\u043E\u0440\u043A\u0430.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "project",
      placement: "lesson-end",
      title: "\u041F\u0440\u043E\u0435\u043A\u0442: 3D Ball",
      whyThisNow: "\u041F\u043E\u043F\u0440\u043E\u0431\u0443\u0439\u0442\u0435 \u043E\u0431\u0443\u0447\u0438\u0442\u044C \u0430\u0433\u0435\u043D\u0442\u0430 \u0432 \u0440\u0435\u0430\u043B\u044C\u043D\u043E\u0439 3D-\u0441\u0440\u0435\u0434\u0435.",
      ctaLabel: "\u041A \u043F\u0440\u043E\u0435\u043A\u0442\u0443",
      isPrimary: true
    }
  ],
  "project-2": [
    {
      hubId: "project",
      placement: "after-intro",
      title: "\u041F\u0440\u043E\u0435\u043A\u0442: 3D-\u043E\u0445\u043E\u0442\u043D\u0438\u043A",
      whyThisNow: "\u0424\u043B\u0430\u0433\u043C\u0430\u043D\u0441\u043A\u0438\u0439 \u043F\u0440\u043E\u0435\u043A\u0442 \u2014 FoodCollector \u0441 REINFORCE.",
      ctaLabel: "\u041F\u0440\u043E\u0435\u043A\u0442\u044B",
      isPrimary: true
    },
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "\u0421\u0440\u0435\u0434\u0430 FoodCollector",
      whyThisNow: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 3D-\u0441\u0440\u0435\u0434\u044B \u0441\u0431\u043E\u0440\u0430 \u0435\u0434\u044B \u0432 Unity.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "lesson-end",
      title: "REINFORCE \u043D\u0430 \u043F\u0440\u0430\u043A\u0442\u0438\u043A\u0435",
      whyThisNow: "\u041F\u0440\u0438\u043C\u0435\u043D\u0435\u043D\u0438\u0435 Policy Gradient \u0432 \u0440\u0435\u0430\u043B\u044C\u043D\u043E\u043C \u043F\u0440\u043E\u0435\u043A\u0442\u0435.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "project-3": [
    {
      hubId: "project",
      placement: "after-intro",
      title: "\u041F\u0440\u043E\u0435\u043A\u0442: \u0413\u043E\u043D\u043E\u0447\u043D\u044B\u0439 \u0430\u0433\u0435\u043D\u0442",
      whyThisNow: "\u041E\u0431\u0443\u0447\u0435\u043D\u0438\u0435 \u0430\u0433\u0435\u043D\u0442\u0430 \u0433\u043E\u043D\u043E\u0447\u043D\u043E\u043C\u0443 \u0432\u043E\u0436\u0434\u0435\u043D\u0438\u044E \u0447\u0435\u0440\u0435\u0437 SAC.",
      ctaLabel: "\u041F\u0440\u043E\u0435\u043A\u0442\u044B",
      isPrimary: true
    },
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "Ray Perception Sensors",
      whyThisNow: "\u0418\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u043D\u0438\u0435 \u043B\u0443\u0447\u0435\u0432\u044B\u0445 \u0441\u0435\u043D\u0441\u043E\u0440\u043E\u0432 \u0434\u043B\u044F \u0432\u043E\u0441\u043F\u0440\u0438\u044F\u0442\u0438\u044F \u0442\u0440\u0430\u0441\u0441\u044B.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  /* ── Stage 3 ── */
  "sac": [
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "SAC: \u0442\u0435\u043E\u0440\u0438\u044F",
      whyThisNow: "\u042D\u043D\u0442\u0440\u043E\u043F\u0438\u0439\u043D\u0430\u044F \u0440\u0435\u0433\u0443\u043B\u044F\u0440\u0438\u0437\u0430\u0446\u0438\u044F \u0438 \u0434\u0432\u043E\u0439\u043D\u043E\u0439 Q \u2014 \u0434\u0435\u0442\u0430\u043B\u0438 \u0432 \u0445\u0430\u0431\u0435.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "SAC \u043D\u0430 PyTorch",
      whyThisNow: "\u0420\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F \u0434\u0432\u043E\u0439\u043D\u043E\u0433\u043E Q-\u043A\u0440\u0438\u0442\u0438\u043A\u0430 \u0438 soft policy.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: false
    },
    {
      hubId: "math-rl",
      placement: "after-intro",
      title: "\u042D\u043D\u0442\u0440\u043E\u043F\u0438\u0439\u043D\u044B\u0439 \u0431\u043E\u043D\u0443\u0441",
      whyThisNow: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 \u044D\u043D\u0442\u0440\u043E\u043F\u0438\u0439\u043D\u043E\u0439 \u0440\u0435\u0433\u0443\u043B\u044F\u0440\u0438\u0437\u0430\u0446\u0438\u0438 \u0432 SAC.",
      ctaLabel: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430",
      isPrimary: false
    }
  ],
  "multi-agent": [
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "MAPOCA \u0432 Unity",
      whyThisNow: "\u041C\u0443\u043B\u044C\u0442\u0438\u0430\u0433\u0435\u043D\u0442\u043D\u043E\u0435 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u0435 \u0447\u0435\u0440\u0435\u0437 self-play \u0432 ML-Agents.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "project",
      placement: "lesson-end",
      title: "\u041F\u0440\u043E\u0435\u043A\u0442: Soccer",
      whyThisNow: "\u041A\u043E\u043C\u0430\u043D\u0434\u043D\u044B\u0439 \u0444\u0443\u0442\u0431\u043E\u043B \u2014 \u043B\u0443\u0447\u0448\u0438\u0439 \u0441\u043F\u043E\u0441\u043E\u0431 \u0437\u0430\u043A\u0440\u0435\u043F\u0438\u0442\u044C \u043C\u0443\u043B\u044C\u0442\u0438\u0430\u0433\u0435\u043D\u0442\u043D\u044B\u0435 \u043D\u0430\u0432\u044B\u043A\u0438.",
      ctaLabel: "\u041A \u043F\u0440\u043E\u0435\u043A\u0442\u0443",
      isPrimary: false
    },
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "Multi-Agent RL",
      whyThisNow: "\u0422\u0435\u043E\u0440\u0438\u044F \u043C\u0443\u043B\u044C\u0442\u0438\u0430\u0433\u0435\u043D\u0442\u043D\u043E\u0433\u043E \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044F \u0438 self-play.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "curriculum-learning": [
    {
      hubId: "unity-ml-agents",
      placement: "after-core-explanation",
      title: "Curriculum \u0432 Unity",
      whyThisNow: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 curriculum learning \u0432 yaml-\u043A\u043E\u043D\u0444\u0438\u0433\u0435 ML-Agents.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-intro",
      title: "Curriculum \u043F\u043E\u0434\u0445\u043E\u0434",
      whyThisNow: "\u041F\u043E\u0441\u0442\u0435\u043F\u0435\u043D\u043D\u043E\u0435 \u0443\u0441\u043B\u043E\u0436\u043D\u0435\u043D\u0438\u0435 \u0437\u0430\u0434\u0430\u0447 \u0434\u043B\u044F \u0441\u0442\u0430\u0431\u0438\u043B\u044C\u043D\u043E\u0433\u043E \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044F.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "gail": [
    {
      hubId: "deep-rl",
      placement: "after-core-explanation",
      title: "GAIL \u0438 BC",
      whyThisNow: "\u0422\u0435\u043E\u0440\u0438\u044F \u0438\u043C\u0438\u0442\u0430\u0446\u0438\u043E\u043D\u043D\u043E\u0433\u043E \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u044F: Behavioral Cloning \u0438 GAIL.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "unity-ml-agents",
      placement: "after-code",
      title: "\u0414\u0435\u043C\u043E\u043D\u0441\u0442\u0440\u0430\u0446\u0438\u0438 \u0432 Unity",
      whyThisNow: "\u0417\u0430\u043F\u0438\u0441\u044C \u0438 \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u043D\u0438\u0435 \u0434\u0435\u043C\u043E\u043D\u0441\u0442\u0440\u0430\u0446\u0438\u0439 \u0432 ML-Agents.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "onnx-deploy": [
    {
      hubId: "unity-ml-agents",
      placement: "after-core-explanation",
      title: "ONNX \u0432 Unity",
      whyThisNow: "\u042D\u043A\u0441\u043F\u043E\u0440\u0442 \u0438 \u0437\u0430\u043F\u0443\u0441\u043A \u043C\u043E\u0434\u0435\u043B\u0435\u0439 \u0447\u0435\u0440\u0435\u0437 ONNX \u2192 Unity Sentis.",
      ctaLabel: "Unity \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "pytorch",
      placement: "after-code",
      title: "PyTorch \u2192 ONNX",
      whyThisNow: "\u041A\u043E\u043D\u0432\u0435\u0440\u0442\u0430\u0446\u0438\u044F PyTorch-\u043C\u043E\u0434\u0435\u043B\u0438 \u0432 \u0444\u043E\u0440\u043C\u0430\u0442 ONNX.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: true
    }
  ],
  "hyperopt": [
    {
      hubId: "pytorch",
      placement: "after-core-explanation",
      title: "\u0413\u0438\u043F\u0435\u0440\u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u044B PyTorch",
      whyThisNow: "Learning rate, batch size, \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u0430 \u2014 \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 \u0432 PyTorch.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-intro",
      title: "\u0413\u0438\u043F\u0435\u0440\u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u044B RL",
      whyThisNow: "\u0421\u043F\u0435\u0446\u0438\u0444\u0438\u043A\u0430 \u043F\u043E\u0434\u0431\u043E\u0440\u0430 \u0433\u0438\u043F\u0435\u0440\u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u043E\u0432 \u0432 RL vs supervised learning.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "fca-rl",
      placement: "after-code",
      title: "FCA \u0434\u043B\u044F \u0433\u0438\u043F\u0435\u0440\u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u043E\u0432",
      whyThisNow: "\u0421\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u0440\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442\u043E\u0432 sweep \u0438 \u0432\u044B\u0431\u043E\u0440 \u0437\u043E\u043D \u0434\u043B\u044F \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0438\u0445 \u044D\u043A\u0441\u043F\u0435\u0440\u0438\u043C\u0435\u043D\u0442\u043E\u0432.",
      ctaLabel: "FCA \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "nn-architectures": [
    {
      hubId: "pytorch",
      placement: "after-core-explanation",
      title: "\u0410\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u044B \u0432 PyTorch",
      whyThisNow: "CNN, LSTM, Attention \u2014 \u0440\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F \u0432 PyTorch \u0434\u043B\u044F RL.",
      ctaLabel: "PyTorch \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "deep-rl",
      placement: "after-intro",
      title: "\u0412\u044B\u0431\u043E\u0440 \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u044B",
      whyThisNow: "\u041A\u0430\u043A\u0430\u044F \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u0430 \u043F\u043E\u0434\u0445\u043E\u0434\u0438\u0442 \u0434\u043B\u044F \u0440\u0430\u0437\u043D\u044B\u0445 \u0442\u0438\u043F\u043E\u0432 \u043D\u0430\u0431\u043B\u044E\u0434\u0435\u043D\u0438\u0439.",
      ctaLabel: "Deep RL \u0445\u0430\u0431",
      isPrimary: true
    },
    {
      hubId: "math-rl",
      placement: "after-code",
      title: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 \u043D\u0435\u0439\u0440\u043E\u0441\u0435\u0442\u0435\u0439",
      whyThisNow: "\u041E\u0431\u0440\u0430\u0442\u043D\u043E\u0435 \u0440\u0430\u0441\u043F\u0440\u043E\u0441\u0442\u0440\u0430\u043D\u0435\u043D\u0438\u0435 \u0438 \u0433\u0440\u0430\u0434\u0438\u0435\u043D\u0442\u043D\u044B\u0439 \u043F\u043E\u0442\u043E\u043A.",
      ctaLabel: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430",
      isPrimary: false
    },
    {
      hubId: "fca-rl",
      placement: "lesson-end",
      title: "FCA \u0434\u043B\u044F \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440",
      whyThisNow: "\u0424\u043E\u0440\u043C\u0430\u043B\u044C\u043D\u044B\u0439 \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442 \u0434\u043B\u044F \u0441\u0440\u0430\u0432\u043D\u0435\u043D\u0438\u044F \u0438 \u0432\u044B\u0431\u043E\u0440\u0430 \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u044B \u043F\u043E\u0434 \u0437\u0430\u0434\u0430\u0447\u0443.",
      ctaLabel: "FCA \u0445\u0430\u0431",
      isPrimary: false
    }
  ],
  "deployment": [
    {
      hubId: "project",
      placement: "lesson-end",
      title: "\u0424\u0438\u043D\u0430\u043B\u044C\u043D\u044B\u0439 \u043F\u0440\u043E\u0435\u043A\u0442",
      whyThisNow: "\u041E\u0431\u044A\u0435\u0434\u0438\u043D\u0438\u0442\u0435 \u0432\u0441\u0435 \u0437\u043D\u0430\u043D\u0438\u044F \u0432 \u0438\u0442\u043E\u0433\u043E\u0432\u043E\u043C \u043F\u0440\u043E\u0435\u043A\u0442\u0435 \u0441 \u0434\u0435\u043F\u043B\u043E\u0435\u043C.",
      ctaLabel: "\u041A \u043F\u0440\u043E\u0435\u043A\u0442\u0443",
      isPrimary: true
    }
  ]
};

// src/content/learningMap.ts
function linksFor(slug) {
  return LESSON_CONTEXT_LINKS[slug] ?? [];
}
var LEARNING_MAP = [
  {
    id: "stage-1",
    slug: "stage-1",
    title: "\u041D\u043E\u0432\u0438\u0447\u043E\u043A",
    description: "\u0424\u0443\u043D\u0434\u0430\u043C\u0435\u043D\u0442: \u0442\u0435\u043E\u0440\u0438\u044F, \u043E\u043A\u0440\u0443\u0436\u0435\u043D\u0438\u0435, \u043F\u0435\u0440\u0432\u044B\u0439 \u0430\u0433\u0435\u043D\u0442, \u0431\u0430\u0437\u043E\u0432\u044B\u0435 \u0430\u043B\u0433\u043E\u0440\u0438\u0442\u043C\u044B \u0438 \u0441\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u0438 \u0438\u0441\u0441\u043B\u0435\u0434\u043E\u0432\u0430\u043D\u0438\u044F.",
    tag: "FREE",
    weeks: 6,
    lessons: [
      { id: "1-1", slug: "basics-rl", title: "\u0427\u0442\u043E \u0442\u0430\u043A\u043E\u0435 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u0435 \u0441 \u043F\u043E\u0434\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u0438\u0435\u043C?", type: "lesson", path: "/courses/1-1", contextLinks: linksFor("basics-rl") },
      { id: "1-2", slug: "setup-pytorch-unity", title: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u043A\u0430 \u043E\u043A\u0440\u0443\u0436\u0435\u043D\u0438\u044F: PyTorch + Unity ML-Agents", type: "lesson", path: "/courses/1-2", contextLinks: linksFor("setup-pytorch-unity") },
      { id: "1-3", slug: "mdp", title: "\u041C\u0430\u0440\u043A\u043E\u0432\u0441\u043A\u0438\u0435 \u043F\u0440\u043E\u0446\u0435\u0441\u0441\u044B \u043F\u0440\u0438\u043D\u044F\u0442\u0438\u044F \u0440\u0435\u0448\u0435\u043D\u0438\u0439 (MDP)", type: "lesson", path: "/courses/1-3", contextLinks: linksFor("mdp") },
      { id: "1-4", slug: "q-learning-tabular", title: "Q-Learning: \u0442\u0430\u0431\u043B\u0438\u0447\u043D\u044B\u0439 \u043C\u0435\u0442\u043E\u0434", type: "lesson", path: "/courses/1-4", contextLinks: linksFor("q-learning-tabular") },
      { id: "1-5", slug: "cartpole", title: "CartPole \u2014 \u0442\u0432\u043E\u0439 \u043F\u0435\u0440\u0432\u044B\u0439 RL-\u0430\u0433\u0435\u043D\u0442", type: "lesson", path: "/courses/1-5", contextLinks: linksFor("cartpole") },
      { id: "1-6", slug: "basic-dqn", title: "DQN \u0441 \u043D\u0443\u043B\u044F \u043D\u0430 PyTorch", type: "lesson", path: "/courses/1-6", contextLinks: linksFor("basic-dqn") },
      { id: "1-7", slug: "exploration-exploitation", title: "Exploration vs Exploitation", type: "lesson", path: "/courses/1-7", contextLinks: linksFor("exploration-exploitation") },
      { id: "p-1", slug: "project-1", title: '\u041F\u0440\u043E\u0435\u043A\u0442-1: "\u0411\u0430\u043B\u0430\u043D\u0441 \u0432 3D"', type: "project", path: "/courses/project-1", contextLinks: linksFor("project-1") }
    ]
  },
  {
    id: "stage-2",
    slug: "stage-2",
    title: "\u0421\u0440\u0435\u0434\u043D\u0438\u0439",
    description: "Policy Gradient, PPO, \u043D\u0435\u043F\u0440\u0435\u0440\u044B\u0432\u043D\u044B\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044F, \u043F\u0430\u0440\u0430\u043B\u043B\u0435\u043B\u044C\u043D\u044B\u0435 \u0441\u0440\u0435\u0434\u044B \u0438 \u043C\u043E\u043D\u0438\u0442\u043E\u0440\u0438\u043D\u0433.",
    tag: "PRO",
    weeks: 6,
    lessons: [
      { id: "2-1", slug: "policy-gradient", title: "Policy Gradient \u0438 \u0442\u0435\u043E\u0440\u0435\u043C\u0430 \u0433\u0440\u0430\u0434\u0438\u0435\u043D\u0442\u0430", type: "lesson", path: "/courses/2-1", contextLinks: linksFor("policy-gradient") },
      { id: "2-2", slug: "ppo", title: "PPO \u2014 \u0440\u0435\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u044F \u0441 \u043D\u0443\u043B\u044F", type: "lesson", path: "/courses/2-2", contextLinks: linksFor("ppo") },
      { id: "2-3", slug: "continuous-actions", title: "\u041D\u0435\u043F\u0440\u0435\u0440\u044B\u0432\u043D\u044B\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044F \u0438 Actor-Critic", type: "lesson", path: "/courses/2-3", contextLinks: linksFor("continuous-actions") },
      { id: "2-4", slug: "reward-shaping", title: "Reward Shaping", type: "lesson", path: "/courses/2-4", contextLinks: linksFor("reward-shaping") },
      { id: "2-5", slug: "parallel-envs", title: "\u041F\u0430\u0440\u0430\u043B\u043B\u0435\u043B\u044C\u043D\u044B\u0435 \u0441\u0440\u0435\u0434\u044B", type: "lesson", path: "/courses/2-5", contextLinks: linksFor("parallel-envs") },
      { id: "2-6", slug: "tensorboard-wandb", title: "TensorBoard \u0438 W&B", type: "lesson", path: "/courses/2-6", contextLinks: linksFor("tensorboard-wandb") },
      { id: "p-2", slug: "project-2", title: "\u041F\u0440\u043E\u0435\u043A\u0442: 3D-\u043E\u0445\u043E\u0442\u043D\u0438\u043A", type: "project", path: "/courses/project-2", contextLinks: linksFor("project-2") },
      { id: "p-3", slug: "project-3", title: "\u041F\u0440\u043E\u0435\u043A\u0442: \u0413\u043E\u043D\u043E\u0447\u043D\u044B\u0439 \u0430\u0433\u0435\u043D\u0442", type: "project", path: "/courses/project-3", contextLinks: linksFor("project-3") }
    ]
  },
  {
    id: "stage-3",
    slug: "stage-3",
    title: "\u041F\u0440\u043E\u0434\u0432\u0438\u043D\u0443\u0442\u044B\u0439",
    description: "SAC, \u043C\u0443\u043B\u044C\u0442\u0438\u0430\u0433\u0435\u043D\u0442\u043D\u044B\u0435 \u0441\u0438\u0441\u0442\u0435\u043C\u044B, curriculum learning, GAIL, \u0434\u0435\u043F\u043B\u043E\u0439 \u0438 \u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u044B.",
    tag: "PRO",
    weeks: 8,
    lessons: [
      { id: "3-1", slug: "sac", title: "SAC \u2014 Soft Actor-Critic", type: "lesson", path: "/courses/3-1", contextLinks: linksFor("sac") },
      { id: "3-2", slug: "multi-agent", title: "MA-POCA \u0438 Self-Play", type: "lesson", path: "/courses/3-2", contextLinks: linksFor("multi-agent") },
      { id: "3-3", slug: "curriculum-learning", title: "\u0423\u0447\u0435\u0431\u043D\u044B\u0439 \u043F\u043B\u0430\u043D \u0438 \u0440\u0430\u043D\u0434\u043E\u043C\u0438\u0437\u0430\u0446\u0438\u044F \u0441\u0440\u0435\u0434\u044B", type: "lesson", path: "/courses/3-3", contextLinks: linksFor("curriculum-learning") },
      { id: "3-4", slug: "gail", title: "\u0418\u043C\u0438\u0442\u0430\u0446\u0438\u043E\u043D\u043D\u043E\u0435 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u0435 (GAIL)", type: "lesson", path: "/courses/3-4", contextLinks: linksFor("gail") },
      { id: "3-5", slug: "onnx-deploy", title: "\u0414\u0435\u043F\u043B\u043E\u0439 \u043C\u043E\u0434\u0435\u043B\u0438: ONNX-\u044D\u043A\u0441\u043F\u043E\u0440\u0442 \u0438 \u0438\u043D\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044F \u0432 Unity-\u0441\u0431\u043E\u0440\u043A\u0443", type: "lesson", path: "/courses/3-5", contextLinks: linksFor("onnx-deploy") },
      { id: "3-6", slug: "hyperopt", title: "\u041E\u043F\u0442\u0438\u043C\u0438\u0437\u0430\u0446\u0438\u044F \u0433\u0438\u043F\u0435\u0440\u043F\u0430\u0440\u0430\u043C\u0435\u0442\u0440\u043E\u0432", type: "lesson", path: "/courses/3-6", contextLinks: linksFor("hyperopt") },
      { id: "3-7", slug: "nn-architectures", title: "\u0410\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u044B \u043D\u0435\u0439\u0440\u043E\u0441\u0435\u0442\u0435\u0439", type: "lesson", path: "/courses/3-7", contextLinks: linksFor("nn-architectures") },
      { id: "3-8", slug: "final-project-game", title: "\u0424\u0438\u043D\u0430\u043B\u044C\u043D\u044B\u0439 \u043F\u0440\u043E\u0435\u043A\u0442", type: "lesson", path: "/courses/3-8", contextLinks: linksFor("final-project-game") }
    ]
  }
];

// src/lib/mcp/tools/list-lessons.ts
var list_lessons_default = defineTool({
  name: "list_lessons",
  title: "List course lessons",
  description: "List all stages, lessons and projects of the RL Platform course (Beginner / Intermediate / Advanced).",
  inputSchema: {
    stage: z.enum(["stage-1", "stage-2", "stage-3"]).optional().describe("Optional stage id to filter (stage-1 = Beginner, stage-2 = Intermediate, stage-3 = Advanced).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ stage }) => {
    const stages = stage ? LEARNING_MAP.filter((s) => s.id === stage) : LEARNING_MAP;
    const summary = stages.map((s) => ({
      id: s.id,
      title: s.title,
      tag: s.tag,
      weeks: s.weeks,
      description: s.description,
      lessons: s.lessons.map((l) => ({
        id: l.id,
        title: l.title,
        type: l.type,
        path: l.path
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { stages: summary }
    };
  }
});

// src/lib/mcp/tools/list-hubs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
var HUBS = [
  { id: "pytorch", label: "PyTorch", slug: "pytorch", description: "\u041E\u0441\u043D\u043E\u0432\u044B \u0442\u0435\u043D\u0437\u043E\u0440\u043E\u0432, autograd, \u043D\u0435\u0439\u0440\u043E\u0441\u0435\u0442\u0435\u0439 \u0438 \u043E\u043F\u0442\u0438\u043C\u0438\u0437\u0430\u0446\u0438\u0438 \u0432 PyTorch." },
  { id: "unity-ml-agents", label: "Unity ML-Agents", slug: "unity-ml-agents", description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u043A\u0430, \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430 \u0441\u0440\u0435\u0434\u044B, \u0441\u0435\u043D\u0441\u043E\u0440\u044B \u0438 \u0442\u0440\u0435\u043D\u0438\u0440\u043E\u0432\u043A\u0430 \u0430\u0433\u0435\u043D\u0442\u043E\u0432 \u0432 Unity." },
  { id: "deep-rl", label: "Deep RL", slug: "deep-rl", description: "\u0413\u043B\u0443\u0431\u043E\u043A\u043E\u0435 \u043E\u0431\u0443\u0447\u0435\u043D\u0438\u0435 \u0441 \u043F\u043E\u0434\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u0438\u0435\u043C: DQN, Policy Gradient, Actor-Critic." },
  { id: "project", label: "\u041F\u0440\u043E\u0435\u043A\u0442\u044B", slug: "project", description: "\u041F\u0440\u0430\u043A\u0442\u0438\u0447\u0435\u0441\u043A\u0438\u0435 \u043F\u0440\u043E\u0435\u043A\u0442\u044B: \u043E\u0442 CartPole \u0434\u043E \u043C\u0443\u043B\u044C\u0442\u0438\u0430\u0433\u0435\u043D\u0442\u043D\u043E\u0433\u043E \u0444\u0443\u0442\u0431\u043E\u043B\u0430." },
  { id: "math-rl", label: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u043A\u0430 RL", slug: "math-rl", description: "\u0412\u0435\u0440\u043E\u044F\u0442\u043D\u043E\u0441\u0442\u0438, MDP, \u0443\u0440\u0430\u0432\u043D\u0435\u043D\u0438\u044F \u0411\u0435\u043B\u043B\u043C\u0430\u043D\u0430, \u0433\u0440\u0430\u0434\u0438\u0435\u043D\u0442\u044B \u043F\u043E\u043B\u0438\u0442\u0438\u043A." },
  { id: "fca-rl", label: "\u0418\u0441\u0441\u043B\u0435\u0434\u043E\u0432\u0430\u043D\u0438\u044F RL", slug: "fca-rl", description: "FCA \u0434\u043B\u044F \u0441\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F \u0441\u043E\u0441\u0442\u043E\u044F\u043D\u0438\u0439, \u043B\u0430\u0431\u043E\u0440\u0430\u0442\u043E\u0440\u0438\u0438 \u0438 \u0432\u0438\u0437\u0443\u0430\u043B\u0438\u0437\u0430\u0446\u0438\u0438." }
];
var list_hubs_default = defineTool2({
  name: "list_hubs",
  title: "List knowledge hubs",
  description: "List all knowledge hubs (PyTorch, Unity ML-Agents, Deep RL, Math RL, Projects, Research) with their descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const hubs = HUBS.map((h) => ({ ...h, path: `/hub/${h.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(hubs, null, 2) }],
      structuredContent: { hubs }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's profile (id, name, avatar) from the RL Platform.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("profiles").select("id, name, avatar_url, created_at").eq("id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = data ?? { id: userId, name: null, avatar_url: null, created_at: null };
    return {
      content: [{ type: "text", text: JSON.stringify({ ...profile, email: ctx.getUserEmail() }, null, 2) }],
      structuredContent: { profile: { ...profile, email: ctx.getUserEmail() } }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_testimonials_default = defineTool4({
  name: "list_testimonials",
  title: "List testimonials",
  description: "List testimonials from RL Platform users, ordered by most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("testimonials").select("id, content, rating, created_at, user_id").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-testimonial.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_testimonial_default = defineTool5({
  name: "submit_testimonial",
  title: "Submit a testimonial",
  description: "Create a testimonial for the RL Platform as the signed-in user (10-1000 chars, rating 1-5).",
  inputSchema: {
    content: z3.string().min(10).max(1e3).describe("Testimonial text (10-1000 chars)."),
    rating: z3.number().int().min(1).max(5).describe("Rating from 1 to 5.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, rating }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("testimonials").insert({ user_id: ctx.getUserId(), content, rating }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Testimonial saved (id=${data?.id}).` }],
      structuredContent: { testimonial: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hpbhllpdakxedqzzlwcv";
var mcp_default = defineMcp({
  name: "rl-platform-mcp",
  title: "RL Platform (Cyber Unity Code)",
  version: "0.1.0",
  instructions: "Tools for the RL Platform \u2014 an educational site about Reinforcement Learning, PyTorch and Unity ML-Agents. Use `list_lessons` to browse the 3-stage course, `list_hubs` for the knowledge hubs, `get_my_profile` to see the signed-in user, and `list_testimonials` / `submit_testimonial` for user feedback.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_lessons_default, list_hubs_default, get_my_profile_default, list_testimonials_default, submit_testimonial_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
