// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/list-lessons.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";
import { LEARNING_MAP } from "npm:@/content/learningMap";
var list_lessons_default = defineTool({
  name: "list_lessons",
  title: "List course lessons",
  description: "List all stages, lessons and projects of the RL Platform course (Beginner / Intermediate / Advanced).",
  inputSchema: {
    stage: z.enum(["stage-1", "stage-2", "stage-3"]).optional().describe("Optional stage id to filter (stage-1 = Beginner, stage-2 = Intermediate, stage-3 = Advanced).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ stage }) => {
    const stages = stage ? LEARNING_MAP.filter((s) => s.id === stage) : LEARNING_MAP;
    const summary = stages.map((s) => ({
      id: s.id,
      title: s.title,
      tag: s.tag,
      weeks: s.weeks,
      description: s.description,
      lessons: s.lessons.map((l) => ({
        id: l.id,
        title: l.title,
        type: l.type,
        path: l.path
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { stages: summary }
    };
  }
});

// src/lib/mcp/tools/list-hubs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { SUPPORT_HUBS } from "npm:@/content/hubs";
var list_hubs_default = defineTool2({
  name: "list_hubs",
  title: "List knowledge hubs",
  description: "List all knowledge hubs (PyTorch, Unity ML-Agents, Deep RL, Math RL, Projects, Research) with their descriptions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const hubs = Object.values(SUPPORT_HUBS).map((h) => ({
      id: h.id,
      label: h.label,
      slug: h.slug,
      description: h.shortDescription,
      path: `/hub/${h.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(hubs, null, 2) }],
      structuredContent: { hubs }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's profile (id, name, avatar) from the RL Platform.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data, error } = await supabase.from("profiles").select("id, name, avatar_url, created_at").eq("id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const profile = data ?? { id: userId, name: null, avatar_url: null, created_at: null };
    return {
      content: [{ type: "text", text: JSON.stringify({ ...profile, email: ctx.getUserEmail() }, null, 2) }],
      structuredContent: { profile: { ...profile, email: ctx.getUserEmail() } }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_testimonials_default = defineTool4({
  name: "list_testimonials",
  title: "List testimonials",
  description: "List testimonials from RL Platform users, ordered by most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("testimonials").select("id, content, rating, created_at, user_id").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-testimonial.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_testimonial_default = defineTool5({
  name: "submit_testimonial",
  title: "Submit a testimonial",
  description: "Create a testimonial for the RL Platform as the signed-in user (10-1000 chars, rating 1-5).",
  inputSchema: {
    content: z3.string().min(10).max(1e3).describe("Testimonial text (10-1000 chars)."),
    rating: z3.number().int().min(1).max(5).describe("Rating from 1 to 5.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, rating }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("testimonials").insert({ user_id: ctx.getUserId(), content, rating }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Testimonial saved (id=${data?.id}).` }],
      structuredContent: { testimonial: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hpbhllpdakxedqzzlwcv";
var mcp_default = defineMcp({
  name: "rl-platform-mcp",
  title: "RL Platform (Cyber Unity Code)",
  version: "0.1.0",
  instructions: "Tools for the RL Platform \u2014 an educational site about Reinforcement Learning, PyTorch and Unity ML-Agents. Use `list_lessons` to browse the 3-stage course, `list_hubs` for the knowledge hubs, `get_my_profile` to see the signed-in user, and `list_testimonials` / `submit_testimonial` for user feedback.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_lessons_default, list_hubs_default, get_my_profile_default, list_testimonials_default, submit_testimonial_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
